name: 'Generate DocC Index Page'
description: 'Create index.html for DocC documentation'
author: 'Nikita Vasilev'

inputs:
  version:
    required: true
    description: 'Documentation version'
  project-name:
    required: true
    description: 'Project display name'
  project-description:
    required: true
    description: 'Project description'
  modules:
    required: false
    description: 'JSON array of modules (e.g., [{"name":"ValidatorCore","path":"validatorcore","description":"Core validation functionality"}])'
    default: '[]'

runs:
  using: 'composite'
  steps:
    - name: Generate index.html
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        PROJECT_NAME: ${{ inputs.project-name }}
        PROJECT_DESC: ${{ inputs.project-description }}
        MODULES: ${{ inputs.modules }}
      run: |
        chmod +x "${{ github.action_path }}/generate-index.sh"
        "${{ github.action_path }}/generate-index.sh"